### ISSUE TITLE
Railsテキスト教材詳細ページの実装

### ISSUE THREAD

**Issue by Kagimoto-Eiji** [yanbaru-expert/team_project_51#17]
【注意】「タスク13」はissue番号に置き換えて記載すること

## 実装内容

「#13」完了後に行って下さい

- aタグの下線が入らないように `app/assets/stylesheets/application.scss` に次を追加

```css
/* 全体 */

a:hover {
  text-decoration: none;
}
```

- 一覧ページから詳細ページに移動できるようにする
  - `link_to` のブロックを利用するのがポイント

- マークダウン形式を変換する `redcarpet`, シンタックスハイライトを適用する `rouge` をインストール
  - `coderay` は使用していません

```rb
gem "redcarpet"
gem "rouge"
```

- `app/helpers/markdown_helper.rb` を作成し，次を設定

```rb
module MarkdownHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(render_options)
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end

  private

  def render_options
    {
      filter_html: false, # htmlを無効化
      hard_wrap: true, # 改行を br 要素に変換
      link_attributes: { target: "_blank", rel: "noopener" } # リンクの設定
    }
  end

  def extensions
    {
      autolink: true, # http https ftpで始まる文字列を自動リンク
      fenced_code_blocks: true, # コードブロックを解析
      no_intra_emphasis: true, # 単語内の強調を解析しない
      tables: true, # 	テーブルを解析
      space_after_headers: true, # ヘッダーの先頭のハッシュとハッシュ名の間にスペースを要求
      hard_wrap: true, # 改行を br 要素に変換
      xhtml: true, # xhtml のタグを出力する(Render::XHTMLでは常に有効)
      lax_html_blocks: true # 複数行のコードの前後に空行が不要
      # strikethrough: true, # 取り消し線(~)を解析する
    }
  end
end
```

【重要】 ここで定義した `markdown` メソッドを使うことで，マークダウン形式の文字列を HTML に変換できます

- `app/assets/stylesheets/rouge.scss.erb` を作成し，`Rouge` のシンタックスハイライト用のスタイルを追加

```erb
<%= Rouge::Themes::Github.render(scope: '.highlight') %>
```

- `app/assets/stylesheets/markdown.scss` を作成し，マークダウン専用のスタイルを追加

```scss
@import "bootstrap/scss/bootstrap";

.markdown {
  table {
    @extend .table;
    display: block;
    overflow-x: scroll;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
    border: initial;

    thead {
      background-color: #EEFFFF;
    }
  }

  h1 {
    font-size: 1.75rem;
    text-align: left;
  }

  pre {
    overflow: auto;
    word-wrap: normal;
    white-space: pre;
    background-color: #f6ffff;
    padding: 0.5rem;
    margin: 1rem 0;
    border: 2px dashed #d6dddd;

    code {
      table.rouge-table {
        margin: 0;

        td.rouge-code {
          padding: 0;
          vertical-align: top;

          pre {
            padding: 5px 10px;
          }
        }
      }
    }
  }
}
```

【重要】 `markdown` クラスを付けたタグで囲むことで，マークダウン用のスタイルが適用されます。例として，次をビューファイルに追加して動作確認をしてみましょう。

```erb
<% 
  str = <<~TEXT
  |HTTPメソッド|URL|アクション|役割|
  |---|---|---|---|
  |GET|/users|index|一覧表示|
  |GET|/users/new|new|新規投稿フォーム表示|
  |POST|/users|create|新規投稿処理|
  |GET|/users/:id|show|詳細表示|
  |GET|/users/:id/edit|edit|更新フォーム表示|
  |PATCH|/users/:id|update|更新処理|
  |DELETE|/users/:id|destroy|削除処理|
TEXT
%>
<div class="markdown">
  <%= markdown(str) %>
</div>
```

- 以上を利用して，詳細ページを実装
  - 「タイトル(title)」と「内容(content)」を表示
  - 「内容」はマークダウンを変換した表示ができるようにすること
  - 詳細ページには「読破済み」機能は実装しないこととする

## 参考文献

- [【公式】Redcarpet](https://github.com/vmg/redcarpet)
- [【公式】Rouge](https://github.com/rouge-ruby/rouge)

## 動作確認

- 一覧ページのカードから対応する詳細ページに遷移できる
- 詳細ページで，下図のようにマークダウンを反映したスタイルとなっている

![text-show](public/readme_images/text-show.png)
